//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPresentationFoundation.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPresentationFoundation.Translate.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string away {
            get {
                return ResourceManager.GetString("away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a team!.
        /// </summary>
        public static string chooseTeamWarning {
            get {
                return ResourceManager.GetString("chooseTeamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition selection:.
        /// </summary>
        public static string competitionSelection {
            get {
                return ResourceManager.GetString("competitionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string croatian {
            get {
                return ResourceManager.GetString("croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string exitWarning {
            get {
                return ResourceManager.GetString("exitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of games played:.
        /// </summary>
        public static string gamesPlayed {
            get {
                return ResourceManager.GetString("gamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        public static string goalsDifference {
            get {
                return ResourceManager.GetString("goalsDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals received:.
        /// </summary>
        public static string goalsReceived {
            get {
                return ResourceManager.GetString("goalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string goalsScored {
            get {
                return ResourceManager.GetString("goalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home vs Away.
        /// </summary>
        public static string homeAway {
            get {
                return ResourceManager.GetString("homeAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection!.
        /// </summary>
        public static string internetConnectionWarning {
            get {
                return ResourceManager.GetString("internetConnectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection:.
        /// </summary>
        public static string languageSelection {
            get {
                return ResourceManager.GetString("languageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s 2018.
        /// </summary>
        public static string men_s {
            get {
                return ResourceManager.GetString("men_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        public static string nextStep {
            get {
                return ResourceManager.GetString("nextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of draws:.
        /// </summary>
        public static string numberDraws {
            get {
                return ResourceManager.GetString("numberDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of losses:.
        /// </summary>
        public static string numberLosses {
            get {
                return ResourceManager.GetString("numberLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of wins:.
        /// </summary>
        public static string numberWins {
            get {
                return ResourceManager.GetString("numberWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player position:.
        /// </summary>
        public static string playerPosition {
            get {
                return ResourceManager.GetString("playerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution selection:.
        /// </summary>
        public static string resolutionSelection {
            get {
                return ResourceManager.GetString("resolutionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to FIFA World Cup Desktop App.
        /// </summary>
        public static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s 2019.
        /// </summary>
        public static string women_s {
            get {
                return ResourceManager.GetString("women_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string yellowCards {
            get {
                return ResourceManager.GetString("yellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
